baseURL = "/"
languageCode = "en-us"
title = "Kube for Hugo"
theme = "kube"
description = "Brian J. Knaus's GitHub Home"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Brian J. Knaus" # add your company name
  github = "knausb" # add your github profile name
  twitter = "" # add your twitter profile
  email = "briank.lists@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
