baseurl = "http://knausb.github.io/"
title = "Brian J. Knaus"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Brian J. Knaus"
    bio = "Brian J. Knaus is a quantitative and computational biologist and an evolutionary genomicist. When I'm not doing that I'm probably running in the forest."
    avatar = "img/knausb.png"


[Params]
    subtitle = "Brian J. Knaus's home on GitHub" # Subtitle of your site
    description = "Brian J. Knaus's Personal blog." # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
