---
title: Header files in Rcpp
author: Brian J. Knaus
date: '2017-08-14'
slug: ''
categories: [R]
tags: [R, Rcpp, Header files]
description: 'Header files in Rcpp'
draft: yes
---


In C++ you can create functions in order to help organize your code.
This is helpful as your project grows or if you have a task that is performed by a function that several other functions may call.
However, the functions you create are only visible to the other funcitons that are contained in a single source file.
As your project grows, you may want to distribute your functions among several files.
And if you do create that funcitons that is called by several other functions you may want to put it in its own file.
But how do you get functions in different files to communicate with one another?
The answer is to create header files.
This post demonstrates how to create and use header files within the Rcpp framework.


## A minimal R package


The use of header files is best illustrated by adding them to an R package.
In order to illustrarte their use, we'll need to create a minimal R package to work with.
I suggest using the R package **pkgKitten** which can be installed from CRAN if you do not already have it.


```
R> library(pkgKitten)
R> kitten(name = "myRpackage")
```

You'll also want **devtools** to easily add **Rcpp** to your package.


```
<<<<<<< HEAD
#bash$ cd myRpackage
#bash$ R
R> setwd('myRpackage')
=======
R> setwd("myRpackage")
>>>>>>> 22032faf6d703f10debc0f222a81f3ae6d7290db
R> library(devtools)
R> use_rcpp()
```

And you'll want to follow the directions at the prompt.
My solution was to add lines to the `hello.R` file.
I've also modified this file from the one created by `pkgKitten` to include Roxygen comments.


**File**: R/hello.R
```
#' @title hello
#' @description
#' Says hello.
#' @name hello
#' @param txt something to say hello to
#' 
#' @export
hello <- function(txt = "world") {
    cat("Hello, ", txt, "\n")
}

#' @useDynLib myRpackage
#' @importFrom Rcpp sourceCpp
NULL
```

You should now be able to build and check your package.


```
bash$ R CMD build myRpackage
bash$ R CMD check --as-cran myRpackage_1.0.tar.gz
```

I actually generate two note, so its not a completely clean build.

```
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Your Name <your@email.com>’

New submission

* checking DESCRIPTION meta-information ... NOTE
'LinkingTo' field is unused: package has no 'src' directory
```

The first note informs us that this is a new submission, and we can ignore it.
The second note is generated because we have yet to populate the `src/` directory with Rcpp code.
We can ignore this for now as well.



## Header files


We can now add a header file as well as some Rcpp code files to our package.
We'll add three files.
The first file will be named `modString.h`.
This is our header file and it declares our function.
The second file will be named `modString.cpp`.
This is the function that is declared in the header file.
Lastly, we'll create `myFunction.cpp`.
This is Rcpp code that will call the function that is declared in the header file.
These files are presented below.


**File**: modString.h
```
#ifndef MODSTRING_H
#define MODSTRING_H

#include <Rcpp.h>
Rcpp::StringVector modString(Rcpp::StringVector myStringV);

#endif
```

Note the inclusion of the following code.


```
#ifndef MODSTRING_H
#define MODSTRING_H
...
#endif
```

This is the 'header guard' and protects you from making multiple definitions of this code.
This should always be a part of your header files.


**File**: modString.cpp
```
#include <string>
#include <sstream>
#include <Rcpp.h>

Rcpp::StringVector modString(Rcpp::StringVector myStringV)
{
  if(myStringV.size() > 1){
    myStringV[1] = "Rcpp";
  }
  return myStringV;
}
```

**File**: myFunction.cpp
```
#include <Rcpp.h>
#include "modString.h"

//' @title myFunction
//' @description
//' Modify a string in Rcpp.
//' @name myFunction
//' @param x a vector of strings
//' @examples
//' myFunction(x=c('Hello', "C++", 'header', 'files'))
//' 
//' @export
// [[Rcpp::export]]
Rcpp::StringVector myFunction(Rcpp::StringVector x) {
  x = modString(x);
  return x;
}
```


We'll want to remove the existing `NAMESPACE` file so that Roxygen can create its own.
Then we'll want to document the project using `devtools`.


```
bash$ cd myRproject
bash$ rm NAMESPECE
bash$ R
R> devtools::document()
R> q()
bash$ cd ..
```

We should now be able to build and check our code again.


```
bash$ R CMD build myRpackage
bash$ R CMD check --as-cran myRpackage_1.0.tar.gz
```

I still generate two notes, but the second one is different.


```
* checking compiled code ... NOTE
File ‘myRpackage/libs/myRpackage.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

It is good practice to register native routines and to disable symbol
search.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```

If this were an actual package we would want to address this.
Help can be found at these links.

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Registering-native-routines
http://dirk.eddelbuettel.com/blog/2017/03/29/#001_easy_package_registration
http://dirk.eddelbuettel.com/blog/2017/03/30/#002_even_easier_package_registration


We're just building an example here that will be deleted instead of being submitted to CRAN, so we'll ignore this here.


## Usage


We should now be able to install our package and test it.

```
R> install.packages("myRpackage_1.0.tar.gz", repos = NULL, type="source")
R> library('myRpackage')
R> myFunction(x=c('Hello', "C++", 'header', 'files'))
```



## Links

These are sources for information I used to create this post.

[Headers and Includes](http://www.cplusplus.com/forum/articles/10627/) at cplusplus.com.    
[Header files](http://www.learncpp.com/cpp-tutorial/19-header-files/) at LearnCpp.com.    
[pkgKitten](https://CRAN.R-project.org/package=pkgKitten) at CRAN, and at [dirk.eddelbuettel.com ](http://dirk.eddelbuettel.com/code/pkgkitten.html) (because it has a cute picture).    


In order to find examples of header files used in R packages you can search GitHub using the following query.



```
user:cran extension:.h
```

Make sure you search for 'Code' instead of the default search of 'Repositories' so that you return code examples.

