---
title: CRAN memory error
author: Brian J. Knaus
date: '2017-06-12'
slug: cran-memory-error
categories: [R]
tags: [R, Rcpp, ASAN, UBSAN]
description: ''
draft: yes
---


I have a package on CRAN where the CRAN tests are reporting a memory error.
In order to use the address sanitizer (ASAN) we need to have a version of R that has been compiled specially to make use of it.
In a previous post I described how we can use [Docker to run rocker images](../running-r-in-docker/) so we do not have to change our system R.
I've also validated the [ASAN is working](../validating-asan/).
We're alost ready to diagnose our issue.
First we'll need to install some software.
We'll also need to handle an R library issue.


## Installing software


In orderer to build the vignettes we'll need a few dependencies from outside R.
We can install these in our Docker instance in a manner similar to a typical system.


```{R, eval = FALSE}
apt-get update
apt-get install pandoc qpdf libssl-dev libssh2-1-dev
```


We'll also need to install some package dependencies.
We can do this from the shell as follows.


```{R, eval = FALSE}
R -e 'install.packages(c("ape", "dplyr", "knitr", "poppr", "Rcpp", "memuse", "pinfsc50", "rmarkdown", "testthat", "tidyr", "vegan", "viridisLite"), dependencies = TRUE, lib = "/usr/local/lib/R/site-library")'
```


This actually take a bit due to the number of packages that are needed.


## Build and check the package


You should now be able to build and check your package.


```{R, eval = FALSE}
cd Rsource
R CMD build vcfR/
R CMD check --as-cran vcfR_1.5.0.9000.tar.gz
```



