---
title: Header files in Rcpp
author: Brian J. Knaus
date: '2017-08-14'
slug: ''
categories: [R]
tags: [R, Rcpp, Header files]
description: 'Header files in Rcpp'
draft: yes
---


In C++ you can create functions in order to help organize your code.
This is helpful as your project grows or if you have a task that is performed by a function that several other functions may call.
However, the functions you create are only visible to the other funcitons that are contained in a single source file.
As your project grows, you may want to distribute your functions among several files.
And if you do create that funcitons that is called by several other functions you may want to put it in its own file.
But how do you get functions in different files to communicate with one another?
The answer is to create header files.
This post demonstrates how to create and use header files within the Rcpp framework.


## A minimal package


The use of header files is best illustrated by adding them to an R package.
In order to illustrarte their use, we'll need to create a minimal package to work with.
I suggest using the R package **pkgKitten** which can be installed from CRAN if you do not already have it.


```
R> library(pkgKitten)
R> kitten(name = "myRpackage")
```

You'll also want **devtools** to easily add **Rcpp** to your package.


```
bash$ cd myRpackage
bash$ R
R> library(devtools)
R> use_rcpp()
```

And you'll want to follow the directions at the prompt.
You'll also want to create a C++ source file in the *src/* directory.
I use the RStudio C++ template called 'timesTwo'.
This should result in an R package ready to use Rcpp and ready for us to add a header file and C++ source to.



**File**: R/hello.R
```
## a placeholder
hello <- function(txt = "world") {
    cat("Hello, ", txt, "\n")
}

#' @useDynLib myRpackage
#' @importFrom Rcpp sourceCpp
NULL
```

**File**: src/timesTwo.cpp
```
#include <Rcpp.h>
using namespace Rcpp;


// [[Rcpp::export]]
int timesTwo(int x) {
   return x * 2;
}
```


```
bash$ R CMD build myRpackage
bash$ R CMD check --as-cran myRpackage_1.0.tar.gz
```


## Files


In order to illustrate the use of header files in Rcpp, we'll create three separate files.


**File**: modString.h
```
#ifndef MODSTRING_H
#define MODSTRING_H

#include <Rcpp.h>
Rcpp::StringVector modString(Rcpp::StringVector myStringV);

#endif
```

**File**: modString.cpp
```
#include <string>
#include <sstream>
#include <Rcpp.h>

Rcpp::StringVector modString(Rcpp::StringVector myStringV)
{
  if(myStringV.size() > 1){
    myStringV[1] = "Rcpp";
  }
  return myStringV;
}
```

**File**: myFunction.cpp
```
#include <Rcpp.h>
#include "modString.h"

//' @title modify_string
//' @description
//' Modify a string in Rcpp.
//' @name modify_string
//' @param x a vector of strings
//' @examples
//' modify_string(x=c('Hello', "C++", 'header', 'files'))
//' 
//' @export
// [[Rcpp::export]]
Rcpp::StringVector modify_string(Rcpp::StringVector x) {
  x = modString(x);
  return x;
}
```

## Usage




## Links

These are sources for information I used to create this post.

[Headers and Includes](http://www.cplusplus.com/forum/articles/10627/) at cplusplus.com.    
[Header files](http://www.learncpp.com/cpp-tutorial/19-header-files/) at LearnCpp.com.    
[pkgKitten](https://CRAN.R-project.org/package=pkgKitten) at CRAN, and at [dirk.eddelbuettel.com ](http://dirk.eddelbuettel.com/code/pkgkitten.html) (because it has a cute picture).    


In order to find examples of header files used in R packages you can search GitHub using the following query.



```
user:cran extension:.h
```

Make sure you search for 'Code' instead of the default search of 'Repositories' so that you return code examples.

